[platformio]
workspace_dir = .pio.nosync

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.1
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  bblanchon/ArduinoJson @ ^7.3.1
  tzapu/WiFiManager @ ^2.0.17

build_flags =
;--  0=None, 1=Error, 2=Warning, 3=Info, 4=Debug, 5=Verbose
  -D CORE_DEBUG_LEVEL=3
;--  EPS_LOG_NONE=0, ESP_LOG_ERROR=1, ESP_LOG_WARN=2, ESP_LOG_INFO=3, ESP_LOG_DEBUG=4, 
;--  ESP_LOG_VERBOSE=5  
  -D LOG_LOCAL_LEVEL=ESP_LOG_INFO

  -D PIN_TFT_CS=21
  -D PIN_TFT_DC=22
  -D PIN_TFT_RST=17
  -D PIN_TFT_BL=16
  -D PIN_TFT_SCL=18
  -D PIN_TFT_SDA=23

  -D PIN_ENC_A=32
  -D PIN_ENC_B=33
  -D PIN_ENC_BTN=25
  -D PIN_KEY0=26
  -D PIN_WIFI_ERASE=0

  -D PIN_OUTPUT=27
  -D PIN_TRIGGER=34
  -D PIN_RESET=35

  -D TFT_WIDTH=320
  -D TFT_HEIGHT=240
  -D TFT_ROTATION=1 ;-- 1 or 3

  -D ENCODER_SHORT_PRESS_MS=200
  -D ENCODER_MEDIUM_PRESS_MS=1500
  -D ENCODER_LONG_PRESS_MS=3000
  -D BUTTON_SHORT_PRESS_MS=200
  -D BUTTON_MEDIUM_PRESS_MS=1500
  -D BUTTON_LONG_PRESS_MS=3000

  -D DEFAULT_AP_SSID=\"UTimer\"
  -D DEFAULT_AP_PASSWORD=\"\"
  -D DEFAULT_WIFI_HOSTNAME=\"U-timer\"

  -D DEFAULT_ON_TIME=5
  -D DEFAULT_OFF_TIME=5
  -D DEFAULT_ON_UNIT=1
  -D DEFAULT_OFF_UNIT=1
  -D DEFAULT_REPEAT_COUNT=1
  -D DEFAULT_TRIGGER_MODE=0
  -D DEFAULT_TRIGGER_EDGE=1
  -D DEFAULT_OUTPUT_POLARITY=1
  -D DEFAULT_LOCK_INPUT_DURING_RUN=0
  -D DEFAULT_AUTO_SAVE_LAST_PROFILE=1

build_src_flags =
  -Wall
  -Wextra
